name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{secrets.HUB_USERNAME}}
          password: ${{secrets.HUB_PASSWORD}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            atianxiua/python-openbmclapi:latest
            atianxiua/python-openbmclapi:${{env.RELEASE_VERSION}}
          platforms: linux/amd64, linux/arm64
      - name: Build the Docker image
        run: |
          #apt install -y git && git clone https://github.com/szsk2022/alphafold3 && cd alphafold3
          #cp docker/* .
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/szsk/alphafold3
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/szsk/alphafold3
