name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          apt install -y git && git clone https://github.com/szsk2022/alphafold3 && cd alphafold3
          cp docker/* .
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/szsk/alphafold3
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/szsk/alphafold3
